# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

# R versions
r:
  - oldrel
  - release
  - devel

# Operating systems to build on
os:
  - linux
  - osx

# Linux options
sudo: false
dist: trusty
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'
